### PR TITLE
#680 Replace the ??? with a no-op

### PR DESCRIPTION
**Pull request by doolse**

### CODE REVIEW

**Comment by edalex-ian** [comment]
Link PR to #680

**Comment by edalex-ian** [comment]
Hey @doolse 

Can you give a run down of how this fixes the issue please?

**Comment by doolse** [comment]
`???` is the equivalent of `throw new UnsupportedOperationException()` in java, generally it's generated by the IDE when you implement something as a reminder to actually implement the method. In this case the correct implementation is a no-op.

**Comment by edalex-ian** [comment]
Gotcha, just found this too: https://alvinalexander.com/scala/what-does-three-question-marks-in-scala-mean

Kind of hard to search for `???`.

**Pull request merged**
