### PR TITLE
Issue/858 generalize header

### PR DESCRIPTION
**Pull request by cbeach47**
As per the last CDM, I've setup this PR with a custom code header that is similar to the OpenCast example, but with Apache v2.  The copyright year is now added to the `NOTICE` file. 

Since it's a repo-wide change, I'd like to button up this PR quickly and get it merged.

### CODE REVIEW

**Comment by cbeach47** [comment]
Thanks @ChristianMurphy .  I plan to merge this in tomorrow morning (US time) unless @edalex-ian reviews and has requested changes.

**Comment by SammyIsConfused** [comment]
> Thanks @ChristianMurphy . I plan to merge this in tomorrow morning (US time) unless @edalex-ian reviews and has requested changes.

Hey @cbeach47, @edalex-ian is away at a conference until Friday morning Australian time. Might be worth putting it off til then if you're awaiting his review.

**Comment by SammyIsConfused** [comment]
Also, does this also change the `sbt headerCreate` command?

**Comment by cbeach47** [comment]
Thanks for the heads up @SammyIsConfused , I'll hold off merging until Ian returns then.

The `sbt headerCreate` command will now pick up the custom wording, and in fact, that's how the repo-wide commit in this PR was made - I made the header template changes in `CommonSettings.scala`, and then ran `sbt headerCreate`.

**Pull request merged**
