### PR TITLE
Modify the new item REST API (#718)

### PR DESCRIPTION
**Pull request by PenghaiZhang**
Since the logic of creating a new version of an item has been changed, the new item REST API needs changes as well.

#718

### CODE REVIEW

**Comment by edalex-ian** [comment]
@PenghaiZhang : I'm concerned that this logic is now in two places. Ideally it should be somewhere central, like the `ItemService`. Is it possible to simply have a `newVersion` method in the item service that handles all this, and then we use it in both view layers (i.e. the UI and the REST)?

**Comment by abidingotter** [comment]
@edalex-ian Normally I'd agree, but the REST and "normal UI" methods of saving an item are very different codebases.  But perhaps the check should be somewhere within itemDeserializerService.newItem instead of the REST endpoint itself though.

**Comment by PenghaiZhang** [comment]
> @PenghaiZhang : I'm concerned that this logic is now in two places. Ideally it should be somewhere central, like the `ItemService`. Is it possible to simply have a `newVersion` method in the item service that handles all this, and then we use it in both view layers (i.e. the UI and the REST)?

Thanks Ian. A new method called "isItemInModeration" has been added to ItemService.

**Comment by PenghaiZhang** [comment]
> @edalex-ian Normally I'd agree, but the REST and "normal UI" methods of saving an item are very different codebases. But perhaps the check should be somewhere within itemDeserializerService.newItem instead of the REST endpoint itself though.

Thank you! 
the check now is in ItemEditorServiceImpl.newItemEditor

**Comment by edalex-ian** [comment]
Can we please tweak the message text as part of this.

'A new version of this item cannot be created because there is already a version in moderation.'

**Pull request merged**
